name: Run Tests on Pull Request
on:
  pull_request:
    branches:
      - master  # หรือใช้ branch ที่คุณต้องการ

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'  # เปลี่ยนเวอร์ชัน Go ตามที่คุณใช้งาน
    
    - name: Run Tests
      run: go test -v ./...

    - name: Run Linter
      run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./...
